<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="14" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="213355" started-at="2019-04-02T13:33:31Z" finished-at="2019-04-02T13:37:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="213355" started-at="2019-04-02T13:33:31Z" finished-at="2019-04-02T13:37:04Z">
      <class name="src.User_registration">
        <test-method status="PASS" signature="browser_launch()[pri:1, instance:src.User_registration@326de728]" name="browser_launch" duration-ms="44709" started-at="2019-04-02T19:03:31Z" finished-at="2019-04-02T19:04:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser_launch -->
        <test-method status="PASS" signature="companyname()[pri:2, instance:src.User_registration@326de728]" name="companyname" duration-ms="2605" started-at="2019-04-02T19:04:16Z" finished-at="2019-04-02T19:04:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- companyname -->
        <test-method status="PASS" signature="lastnamereal()[pri:3, instance:src.User_registration@326de728]" name="lastnamereal" duration-ms="1348" started-at="2019-04-02T19:04:18Z" finished-at="2019-04-02T19:04:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lastnamereal -->
        <test-method status="PASS" signature="firstnamereal()[pri:4, instance:src.User_registration@326de728]" name="firstnamereal" duration-ms="445" started-at="2019-04-02T19:04:20Z" finished-at="2019-04-02T19:04:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstnamereal -->
        <test-method status="PASS" signature="ph_number_real()[pri:5, instance:src.User_registration@326de728]" name="ph_number_real" duration-ms="2432" started-at="2019-04-02T19:04:20Z" finished-at="2019-04-02T19:04:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ph_number_real -->
        <test-method status="PASS" signature="email_real()[pri:6, instance:src.User_registration@326de728]" name="email_real" duration-ms="2623" started-at="2019-04-02T19:04:23Z" finished-at="2019-04-02T19:04:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- email_real -->
        <test-method status="PASS" signature="password_real()[pri:7, instance:src.User_registration@326de728]" name="password_real" duration-ms="2459" started-at="2019-04-02T19:04:25Z" finished-at="2019-04-02T19:04:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- password_real -->
        <test-method status="PASS" signature="confirm_password_real()[pri:8, instance:src.User_registration@326de728]" name="confirm_password_real" duration-ms="2399" started-at="2019-04-02T19:04:28Z" finished-at="2019-04-02T19:04:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm_password_real -->
        <test-method status="PASS" signature="checkbox()[pri:9, instance:src.User_registration@326de728]" name="checkbox" duration-ms="7219" started-at="2019-04-02T19:04:30Z" finished-at="2019-04-02T19:04:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkbox -->
        <test-method status="PASS" signature="yopmail()[pri:10, instance:src.User_registration@326de728]" name="yopmail" duration-ms="68493" started-at="2019-04-02T19:04:37Z" finished-at="2019-04-02T19:05:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yopmail -->
        <test-method status="PASS" signature="admin()[pri:12, instance:src.User_registration@326de728]" name="admin" duration-ms="3051" started-at="2019-04-02T19:05:46Z" finished-at="2019-04-02T19:05:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- admin -->
        <test-method status="FAIL" signature="User_submit()[pri:13, instance:src.User_registration@326de728]" name="User_submit" duration-ms="63657" started-at="2019-04-02T19:05:49Z" finished-at="2019-04-02T19:06:52Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at src.User_registration.User_submit(User_registration.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- User_submit -->
        <test-method status="FAIL" signature="user()[pri:14, instance:src.User_registration@326de728]" name="user" duration-ms="11678" started-at="2019-04-02T19:06:52Z" finished-at="2019-04-02T19:07:04Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at src.User_registration.user(User_registration.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user -->
        <test-method status="FAIL" signature="test()[pri:15, instance:src.User_registration@326de728]" name="test" duration-ms="137" started-at="2019-04-02T19:07:04Z" finished-at="2019-04-02T19:07:04Z">
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'RISING', ip: '192.168.2.7', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.42.591088 (7b2b2dca23cca0..., userDataDir: C:\Users\rising1\AppData\Lo...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:62745}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 73.0.3683.86, webStorageEnabled: true}
Session ID: 654154df04da0e5d2bd310aedc393e23
*** Element info: {Using=xpath, value=//*[@id="wrapper"]/div[5]/div[2]/div/section/div/div/aside/div/ui-view/ui-view/button}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'RISING', ip: '192.168.2.7', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.42.591088 (7b2b2dca23cca0..., userDataDir: C:\Users\rising1\AppData\Lo...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:62745}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 73.0.3683.86, webStorageEnabled: true}
Session ID: 654154df04da0e5d2bd310aedc393e23
*** Element info: {Using=xpath, value=//*[@id="wrapper"]/div[5]/div[2]/div/section/div/div/aside/div/ui-view/ui-view/button}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:319)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:421)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:311)
	at src.User_registration.test(User_registration.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- src.User_registration -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
